server: 
  port: 8081
  servlet:
    context-path: /hotel

app:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: hotel
    password: oracle
    pool-properties:
      initial-size: 30
      max-active: 10