server: 
  servlet:
    path: /api
spring:
  autoconfigure:
    exclude: "org.springframework.boot.autoconfigure.session.SessionAutoConfiguration"
  main:
    banner-mode: 'off'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        transaction:
          coordinator-class: jdbc
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          batch-size: 20
  profiles:
    active: dev