package com.informatique.gov.helpdesk.support.dataenum;

public enum ExceptionClassNameEnum {
	PreConditionRequiredException, ResourceModifiedException, ResourceNotFoundException, ResourceNotModifiedException, JudicialWarrantInternalException, InvalidRequestStatusException, SingleResourceVersionNotProvidedException, SingleResourceModifiedException, SingleResourceNotFoundException,ResourceIntegrityException,RequestTypeAttachmentTypeException
}
