#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
#regarding the 'off' issue of spring.main.banner-mode please have a look at https://github.com/spring-projects/spring-boot/commit/43b8e65eee7c23a7f7c3b61f8a436dc9cbfe5b96
server: 
  servlet:
     context-path: /sd
     path: /api
spring:
  main:
    banner-mode: 'off'
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        transaction:
          coordinator-class: jdbc
        dialect: org.hibernate.dialect.Oracle12cDialect
        jdbc:
          batch-size: 20
  profiles:
    active: dev