alter session set "_ORACLE_SCRIPT"=true;
create user hotel
  identified by oracle;
-- Grant/Revoke role privileges 
grant connect to hotel;
grant dba to hotel;
grant resource to hotel;


CREATE TABLE USERS 
(
  ID NUMBER(5, 0) NOT NULL 
, Name VARCHAR2(100) NOT NULL 
, Password VARCHAR2(100) NOT NULL 
, CONSTRAINT USER_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE USERS 
ADD (ROLE_ID NUMBER(1) );



CREATE TABLE APP_ROLE 
(
  ID NUMBER(1) NOT NULL 
, CODE VARCHAR2(50 CHAR) NOT NULL 
, ARABIC_NAME VARCHAR2(50) 
, ENGLISH_NAME VARCHAR2(50) NOT NULL 
, CONSTRAINT APP_ROLE_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE APP_USER
ADD CONSTRAINT USER_ROLE_FK FOREIGN KEY
(
  ROLE_ID 
)
REFERENCES APP_ROLE
(
  ID 
)
ENABLE;


CREATE TABLE ROOM 
(
  ID NUMBER(5) NOT NULL 
, TYPE_ID NUMBER(1) NOT NULL 
, RESERVATION_ID NUMBER(5) 
, CONSTRAINT ROOM_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);


CREATE TABLE RESERVATION 
(
  ID NUMBER(5) NOT NULL 
, TYPE_ID NUMBER(1) NOT NULL 
, ROOM_ID NUMBER(5) 
, CUSTOMER_ID NUMBER(5) 
, CREATOR_ID NUMBER(5) 
, DURATION NUMBER(5) 
, DATE_CREATED TIMESTAMP
, CONSTRAINT RESERVATION_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);




CREATE TABLE TYPES
(
  ID NUMBER(1) NOT NULL 
, CODE VARCHAR2(50) 
, CONSTRAINT TYPES_ID_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);



   CREATE SEQUENCE  hotel."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
    CREATE SEQUENCE  hotel."RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
CREATE SEQUENCE  hotel."ROOM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;


-------------------------------------------------------
--  DDL for Table CONFIGURATION
--------------------------------------------------------

  CREATE TABLE hotel."CONFIGURATION" 
   (	"KEY" VARCHAR2(500 BYTE), 
	"VALUE" VARCHAR2(500 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CNFG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX hotel."CNFG_PK" ON hotel."CONFIGURATION" ("KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CONFIGURATION
--------------------------------------------------------

  ALTER TABLE hotel."CONFIGURATION" ADD CONSTRAINT "CNFG_PK" PRIMARY KEY ("KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE hotel."CONFIGURATION" MODIFY ("KEY" NOT NULL ENABLE);
  
  
  


=========================================




--------------------------------------------------------
--  File created - Monday-September-02-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMAIL_NOTIFICATION
--------------------------------------------------------

  

--------------------------------------------------------
--  DDL for Table ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "ERROR_LOG" 
   (	"ID" NUMBER, 
	"STACK_TRACE" CLOB, 
	"TICKET_SERIAL" VARCHAR2(200 BYTE), 
	"USER_NAME" VARCHAR2(500 BYTE), 
	"CREATE_DATE" TIMESTAMP (6)
   ) ;
/

--------------------------------------------------------
--  DDL for Table SPRING_SESSION
--------------------------------------------------------

  CREATE TABLE "SPRING_SESSION" 
   (	"SESSION_ID" CHAR(36 BYTE), 
	"CREATION_TIME" NUMBER(19,0), 
	"LAST_ACCESS_TIME" NUMBER(19,0), 
	"MAX_INACTIVE_INTERVAL" NUMBER(10,0), 
	"PRINCIPAL_NAME" VARCHAR2(100 CHAR)
   ) ;
/
--------------------------------------------------------
--  DDL for Table SPRING_SESSION_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "SPRING_SESSION_ATTRIBUTES" 
   (	"SESSION_ID" CHAR(36 BYTE), 
	"ATTRIBUTE_NAME" VARCHAR2(200 CHAR), 
	"ATTRIBUTE_BYTES" BLOB
   ) ;
/

--------------------------------------------------------
--  DDL for Index SPRING_SESSION_IX2
--------------------------------------------------------

  CREATE INDEX "SPRING_SESSION_IX2" ON "SPRING_SESSION" ("LAST_ACCESS_TIME") 
  ;
/
--------------------------------------------------------
--  DDL for Index SPRING_SESSION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING_SESSION_PK" ON "SPRING_SESSION" ("SESSION_ID") 
  ;
/
--------------------------------------------------------
--  DDL for Index SPRING_SESSION_ATTRIBUTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING_SESSION_ATTRIBUTES_PK" ON "SPRING_SESSION_ATTRIBUTES" ("SESSION_ID", "ATTRIBUTE_NAME") 
  ;
/

--------------------------------------------------------
--  Constraints for Table SPRING_SESSION
--------------------------------------------------------

  ALTER TABLE "SPRING_SESSION" ADD CONSTRAINT "SPRING_SESSION_PK" PRIMARY KEY ("SESSION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPRING_SESSION" MODIFY ("MAX_INACTIVE_INTERVAL" NOT NULL ENABLE);
  ALTER TABLE "SPRING_SESSION" MODIFY ("LAST_ACCESS_TIME" NOT NULL ENABLE);
  ALTER TABLE "SPRING_SESSION" MODIFY ("CREATION_TIME" NOT NULL ENABLE);
  ALTER TABLE "SPRING_SESSION" MODIFY ("SESSION_ID" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Constraints for Table SPRING_SESSION_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SPRING_SESSION_ATTRIBUTES_PK" PRIMARY KEY ("SESSION_ID", "ATTRIBUTE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SPRING_SESSION_ATTRIBUTES" MODIFY ("ATTRIBUTE_BYTES" NOT NULL ENABLE);
  ALTER TABLE "SPRING_SESSION_ATTRIBUTES" MODIFY ("ATTRIBUTE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING_SESSION_ATTRIBUTES" MODIFY ("SESSION_ID" NOT NULL ENABLE);
/
--------------------------------------------------------
--  Ref Constraints for Table SPRING_SESSION_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "SPRING_SESSION_ATTRIBUTES" ADD CONSTRAINT "SPRING_SESSION_ATTRIBUTES_FK" FOREIGN KEY ("SESSION_ID")
	  REFERENCES "SPRING_SESSION" ("SESSION_ID") ON DELETE CASCADE ENABLE;
/
