alter session set "_ORACLE_SCRIPT"=true;
create user hotel
  identified by oracle;
-- Grant/Revoke role privileges 
grant connect to hotel;
grant dba to hotel;
grant resource to hotel;


--------------------------------------------------------
--  File created - Friday-December-20-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOTEL"."RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ROOM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOTEL"."ROOM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOTEL"."USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 241 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table APP_ROLE
--------------------------------------------------------

  CREATE TABLE "HOTEL"."APP_ROLE" 
   (	"ID" NUMBER(1,0), 
	"CODE" VARCHAR2(50 CHAR), 
	"ENGLISH_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONFIGURATION
--------------------------------------------------------

  CREATE TABLE "HOTEL"."CONFIGURATION" 
   (	"KEY" VARCHAR2(500 BYTE), 
	"VALUE" VARCHAR2(500 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ERROR_LOG
--------------------------------------------------------

  CREATE TABLE "HOTEL"."ERROR_LOG" 
   (	"ID" NUMBER, 
	"STACK_TRACE" CLOB, 
	"TICKET_SERIAL" VARCHAR2(200 BYTE), 
	"USER_NAME" VARCHAR2(500 BYTE), 
	"CREATE_DATE" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("STACK_TRACE") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "HOTEL"."RESERVATION" 
   (	"ID" NUMBER(5,0), 
	"TYPE_ID" NUMBER(1,0), 
	"ROOM_ID" NUMBER(5,0), 
	"CUSTOMER_ID" NUMBER(5,0), 
	"CREATOR_ID" NUMBER(5,0), 
	"DURATION" NUMBER(5,0), 
	"DATE_CREATED" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROOM
--------------------------------------------------------

  CREATE TABLE "HOTEL"."ROOM" 
   (	"ID" NUMBER(5,0), 
	"TYPE_ID" NUMBER(1,0), 
	"RESERVATION_ID" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table TYPES
--------------------------------------------------------

  CREATE TABLE "HOTEL"."TYPES" 
   (	"ID" NUMBER(1,0), 
	"CODE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "HOTEL"."USERS" 
   (	"ID" NUMBER(5,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"ROLE_ID" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HOTEL.APP_ROLE
SET DEFINE OFF;
Insert into HOTEL.APP_ROLE (ID,CODE,ENGLISH_NAME) values (1,'CUSTOMER','Customer');
Insert into HOTEL.APP_ROLE (ID,CODE,ENGLISH_NAME) values (2,'EMPLOYEE','Employee');
Insert into HOTEL.APP_ROLE (ID,CODE,ENGLISH_NAME) values (3,'MANAGER','manager');
REM INSERTING into HOTEL.CONFIGURATION
SET DEFINE OFF;
Insert into HOTEL.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.security.max-inactive-interval','3600','In seconds');
Insert into HOTEL.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.jpa.show-sql','true',null);
Insert into HOTEL.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('server.port','8089',null);
Insert into HOTEL.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('logging.level.com.informatique.gov.helpdesk','debug','Logging level');
Insert into HOTEL.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('logging.level.org.springframework.security','debug','Logging level');
REM INSERTING into HOTEL.ERROR_LOG
SET DEFINE OFF;
REM INSERTING into HOTEL.RESERVATION
SET DEFINE OFF;
REM INSERTING into HOTEL.ROOM
SET DEFINE OFF;
REM INSERTING into HOTEL.SPRING_SESSION
SET DEFINE OFF;
REM INSERTING into HOTEL.SPRING_SESSION_ATTRIBUTES
SET DEFINE OFF;
REM INSERTING into HOTEL.TYPES
SET DEFINE OFF;
REM INSERTING into HOTEL.USERS
SET DEFINE OFF;
Insert into HOTEL.USERS (ID,NAME,PASSWORD,ROLE_ID) values (1,'admin','123',3);
--------------------------------------------------------
--  DDL for Index ROOM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOTEL"."ROOM_PK" ON "HOTEL"."ROOM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CNFG_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOTEL"."CNFG_PK" ON "HOTEL"."CONFIGURATION" ("KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOTEL"."USER_PK" ON "HOTEL"."USERS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TYPES_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOTEL"."TYPES_ID_PK" ON "HOTEL"."TYPES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESERVATION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOTEL"."RESERVATION_PK" ON "HOTEL"."RESERVATION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index APP_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOTEL"."APP_ROLE_PK" ON "HOTEL"."APP_ROLE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HOTEL"."USERS" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOTEL"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."USERS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TYPES
--------------------------------------------------------

  ALTER TABLE "HOTEL"."TYPES" ADD CONSTRAINT "TYPES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOTEL"."TYPES" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "HOTEL"."RESERVATION" ADD CONSTRAINT "RESERVATION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOTEL"."RESERVATION" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."RESERVATION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_ROLE
--------------------------------------------------------

  ALTER TABLE "HOTEL"."APP_ROLE" ADD CONSTRAINT "APP_ROLE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOTEL"."APP_ROLE" MODIFY ("ENGLISH_NAME" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."APP_ROLE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."APP_ROLE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONFIGURATION
--------------------------------------------------------

  ALTER TABLE "HOTEL"."CONFIGURATION" MODIFY ("KEY" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."CONFIGURATION" ADD CONSTRAINT "CNFG_PK" PRIMARY KEY ("KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROOM
--------------------------------------------------------

  ALTER TABLE "HOTEL"."ROOM" ADD CONSTRAINT "ROOM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOTEL"."ROOM" MODIFY ("TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "HOTEL"."ROOM" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "HOTEL"."USERS" ADD CONSTRAINT "USER_ROLE_FK" FOREIGN KEY ("ROLE_ID")
	  REFERENCES "HOTEL"."APP_ROLE" ("ID") ENABLE;
