Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.security.websocket.allowed-origins','*',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.ucm.ip','192.168.0.44',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.ucm.port','4444',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.ucm.username','weblogic',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.ucm.password','welcome1',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.notification-channels','EMAIL_SMS',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.security.max-inactive-interval','3600','In seconds');
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.jpa.show-sql','true',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('server.port','8081',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('logging.level.com.informatique.gov.helpdesk','debug','Logging level');
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('logging.level.org.springframework.security','debug','Logging level');
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.integration.sms.url','http://ipa:8888/sms-client/service/sms',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.integration.sms.username','admin',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.integration.sms.password','admin1',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.integration.rop.url','http://192.168.0.45:8083/integration/rop/person',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.integration.rop.username','ropuser',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('app.integration.rop.password','"!Nt3gr@T10n"',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.host','smtp.moj.gov.om',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.port','25',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.username','noreply@moj.gov.om',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.password','321noreply',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.protocol','smtp',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.test-connection','false',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.properties.mail.smtp.auth','true',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.properties.mail.smtp.from','noreply@moj.gov.om',null);
Insert into SD.CONFIGURATION (KEY,VALUE,DESCRIPTION) values ('spring.mail.properties.mail.debug','false',null);
