server: 
  port: 8081
  servlet:
    context-path: /sd

app:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sd
    password: oracle
    pool-properties:
      initial-size: 30
      max-active: 10